### ISSUE TITLE
عدم پشتیبانی نود از پروتکل هایی به جز reality

### ISSUE THREAD

**Issue by sepehrEslami81** [Gozargah/Marzban-node#11]
سلام.
نود ها فقط از reality پشتیبانی می کنن و هر کانفیگی به جز اون روی پنل اجرا بشه روی نود کار نمیکنه (من trojan + ws و vmess + ws رو تست کردم). لطفا بررسی کنید یا اگر راه حل داره راه حلش رو بگید چون واقعا لازم دارم به اضافه شدن کانفیگ های به جز reality

**Comment by SaintShit** [comment]
سلام
نود ها دقیقا یک کپی از تنظیمات سرور مرکزی رو دارن. مشکلی که برای شما پیش اومده احتمالا از پیکربندیتونه، لطفا فایل های مربوط به کانفیگ xray رو بزارین تا بررسی کنیم

**Comment by sepehrEslami81** [comment]
متوجه مشکلش شدم. ممنون
