### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by Eidreven** [Gozargah/Marzban-node#14]
Where can I find the installation guide README.rd is empty

**Comment by kastov** [comment]
1. `sudo apt-get update`
2. `curl -fsSL https://get.docker.com | sh`
3. `git clone https://github.com/Gozargah/Marzban-node`
4. `cd Marzban-node`
5. `cat /var/lib/marzban-node/ssl_cert.pem`
6. Paste IP address of node and output from step 5 to main server in node settings.

**Comment by k1trader** [comment]
سلام وقت بخیر مشکل من از شماره سه به بعد هستش وقتی میزنم ارور میده command not found

**Comment by kastov** [comment]
> Hello, good time, my problem is from number three onwards, when I type, it gives an error command not found

try to install git
1. `sudo apt update`
2. `sudo apt install git`

**Comment by DigneZzZ** [comment]
> 1. `sudo apt-get update`
> 2. `curl -fsSL https://get.docker.com | sh`
> 3. `git clone https://github.com/Gozargah/Marzban-node`
> 4. `cd Marzban-node`
> 5. `cat /var/lib/marzban-node/ssl_cert.pem`
> 6. Paste IP address of node and output from step 5 to main server in node settings.

and how to leave the main service after that.py enabled?

**Comment by DigneZzZ** [comment]
so
i can create the main.py service, and push him in autorun.. and its work))

**Comment by DigneZzZ** [comment]
https://openode.ru/topic/526-marzban-node-dobavlyaem-server-v-drugoy-strane-k-nashemu-osnovnomu/

**Comment by amirvp** [comment]
سلام وقت بخیر قبلا سرتیفیکت نود رو روی پنل اصلی میذاشتیم و کار میکرد ، الان میگه سرتفیکیت پنل اصلی رو توی نود کپی کنید ولی هیچ آموزشی برای این کار نیست. باید چکار کنیم؟

**Comment by amirvp** [comment]
> > سلام وقت بخیر قبلا سرتیفیکت نود رو روی پنل اصلی میذاشتیم و کار میکرد ، الان میگه سرتفیکیت پنل اصلی رو توی نود کپی کنید ولی هیچ آموزشی برای این کار نیست. باید چکار کنیم؟
> 
> https://github.com/mdjvd/gozargah.github.io/blob/de4e037db38ec1c1d5519b99bc8002af1f2d8ecd/marzban/fa/docs/marzban-node.md

خیلی ممنونم

**Comment by amirvp** [comment]
> > سلام وقت بخیر قبلا سرتیفیکت نود رو روی پنل اصلی میذاشتیم و کار میکرد ، الان میگه سرتفیکیت پنل اصلی رو توی نود کپی کنید ولی هیچ آموزشی برای این کار نیست. باید چکار کنیم؟
> 
> https://github.com/mdjvd/gozargah.github.io/blob/de4e037db38ec1c1d5519b99bc8002af1f2d8ecd/marzban/fa/docs/marzban-node.md

[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

این ارور رو به من میده ، لطفا راهنمایی ام کنید
