### ISSUE TITLE
مشکل نداشتن دیتا از سرورهای نود

### ISSUE THREAD

**Issue by ndfbit** [Gozargah/Marzban-node#22]
سلام
خدمت دوستان
من سرور رو نود کردم 
کانفیگ های سرور اصلی به خوبی کار میکنند ولی کانفیگهای سرور نود دیتا ندارن
ممنوم میشم راهنمایی کنید

**Comment by DeAref** [comment]
## منم دقیقا همین مشکل رو دارم مستندات رو اینجا پیوست میکنم تا اگر کسی تونست کمک کنه:

### **پنل به درستی متصل است:**
![image](https://github.com/Gozargah/Marzban-node/assets/95649368/6bc37fba-a78f-481c-a0bc-3853a339478e)

### **در قسمت هاست هم با دامین و هم با ایپی اضافه شده است:**
![image](https://github.com/Gozargah/Marzban-node/assets/95649368/df9f3aeb-b530-4fd8-8bbd-2d298a97cab5)


### **فایل داکر:**
![image](https://github.com/Gozargah/Marzban-node/assets/95649368/c28a3298-cfc4-488f-a9ca-a1f4639e47db)

### **فایروال هم خاموش هست:**
![image](https://github.com/Gozargah/Marzban-node/assets/95649368/8c9307d3-1f7d-4a71-937a-efdb5bce9938)

### **ارور موقع اتصال:**
![image](https://github.com/Gozargah/Marzban-node/assets/95649368/1cf368fc-c7cf-4499-a51f-f70b0d2aad7c)


**توی قسمت لاگ هم هیچ کانکشنی نمیاد به سمت نود**
نسخه مرزبان: v0.4.1 (آخرین نسخه)
نسخه مرزبان-نود: آخرین نسخه

نمیدونم برنامه مشکل داره یا من یه جایی رو نتونستم درست کانفیگ کنم
ممنون میشم دوستان کمک کنن

**Comment by SaintShit** [comment]
سلام. باید مطمعن بشین این به دلیل فیلترینگ نیست. برای اینکه بتونین لاگ های ایکس‌ری رو روی نود ببینید، متغیر محیطی DEBUG رو true قرار بدین و کانتینر نودتون رو ری‌استارت کنید. بعد لاگ ها رو بررسی کنید و ببینید درخواست هاتون به سرور نود میاد یا نه، همینطور از پنل، بخش تنظیمات هسته، لاگ لول رو روی debug قرار بدین.

**Comment by DeAref** [comment]
سلام خدمت شما. بعد از برسی متوجه شدم مشکل از warp هست. باید روی سرور نود هم نصب میشد.
تشکر از جوابتون
