### ISSUE TITLE
proxied node connection

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban-node#23]
سلام
وقتی سانسور شدید میشه اتصال نود ایران به سرور مستر خارج خیلی مشکل میشه
تنها راه هایی که ممکنه کار کنن ریورس تونل و اس اس اش هستن
امکانش هست چندین مدل اتصال مختلف اد کنید برای اتصال سرور مستر و نود به هم تا هنگام سانسور شدید هم مشکلی نداشته باشیم؟
با تشکر

**Comment by SaintShit** [comment]
سلام در حال حاضر نود از طریق RPC وصل میشه و نیاز هست که پکت هارو به صورت tcp فروارد کنید
