### ISSUE TITLE
Unrestricted connection between the Marzban-Node and Marzban-Dashboard

### ISSUE THREAD

**Issue by mmx2004** [Gozargah/Marzban-node#26]
When adding a Node in the Marzban-Dashboard, it displays a Certification that ideally needs to be copied into the Node. However, even without copying this Certification, the Node can still be connected to the Dashboard and used without any issues. This presents a significant security flaw that requires immediate attention and resolution.

**Comment by mmx2004** [comment]
But It appears that even the previous version of Marzban-Node lacks sufficient protection against unauthorized use. With the correct version of Marzban-Dashboard, one could potentially utilize another individual's Marzban-Node, which poses a significant security concern. This situation is far from ideal and requires immediate attention to ensure proper security measures are in place.

**Comment by xshayank** [comment]
> This is why marzban removed the old method for nodes , in the new version unauthorized marzban can't connect nodes.

I think they are having this issue in the new version not the old one

**Comment by SaintShit** [comment]
> But It appears that even the previous version of Marzban-Node lacks sufficient protection against unauthorized use. With the correct version of Marzban-Dashboard, one could potentially utilize another individual's Marzban-Node, which poses a significant security concern. This situation is far from ideal and requires immediate attention to ensure proper security measures are in place.

can u provide some details on how this could happen?
