### ISSUE TITLE
License

### ISSUE THREAD

**Issue by parhawm** [Gozargah/Marzban-node#27]
Currently the project contains no license,
so I'm assuming it is copyrighted.
 
I'm therefor suggesting to add an AGPL license or otherwise asking for permission to modify this code.

**Comment by parhawm** [comment]
yes? no? accepted? declined? I'm waiting for an answer.

**Comment by M03ED** [comment]
@SaintShit

**Comment by parhawm** [comment]
@SaintShit

**Comment by SaintShit** [comment]
Hi, thanks for asking. I added license to the repository. you're good to go. also sorry for the late reply.
