### ISSUE TITLE
تغییر پورت اتصال نود

### ISSUE THREAD

**Issue by mnsb13600** [Gozargah/Marzban-node#29]
با سلام به دوستان
چطوری می شود پورت اتصال نود به سرور اصلی را تغییر داد
می خواهم روی nat استفاده کنم

**Comment by parhawm** [comment]
@mnsb13600 اگه رو داکره با کانفیگ داکر و یا فایل .env. اگر نه از .env میشه تغییر داده.

**Comment by mnsb13600** [comment]
> Edit your docker-compose file like this, and setup variables in `environment` section
> 
> ```
> services:
>   marzban-node:
>     # build: .
>     image: gozargah/marzban-node:latest
>     restart: always
>     network_mode: host
> 
>     environment:
>       SERVICE_PORT: 2000
>       XRAY_API_PORT: 2001
>       SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"
> 
>     volumes:
>       - /var/lib/marzban-node:/var/lib/marzban-node
> ```
> 
> Reference: https://gozargah.github.io/marzban/docs/marzban-node

میشه بفرمایید ادرس دقیق این فایل کجای سرور است

**Comment by mnsb13600** [comment]
> اگه رو داکره با کانفیگ داکر و یا فایل .env. اگر نه از .env میشه تغییر داد.

مسیر فایل را می توانید بگویید

**Comment by parhawm** [comment]
@mnsb13600 همون راه حلی که رفیقمون بالا گفته رو انجام بده برای داکر

**Comment by mnsb13600** [comment]
> @mnsb13600 همون راه حلی که رفیقمون بالا گفته رو انجام بده برای داکر

متصل نشد
