### ISSUE TITLE
CF proxied node

### ISSUE THREAD

**Issue by Sinicyn78** [Gozargah/Marzban-node#30]
How to connect a node to the main if the node’s domain is proxied to CF?

**Comment by M03ED** [comment]
just use ip :////

**Comment by Sinicyn78** [comment]
> just use ip :////

doesn't connect. if I remove proxying on CF, it connects

**Comment by realartin** [comment]
@Sinicyn78 fill host field with sni

**Comment by Sinicyn78** [comment]
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/06d9d674-e821-4e2c-9edf-369877ac2d2c)
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/9f224700-4d81-48a4-8a2c-c4e468e163df)
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/bc1d0822-475c-43d7-99d9-9538cc8b5fc2)
Can't connect to CF ports either

**Comment by Sinicyn78** [comment]
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/0c6955ef-6ec6-421f-80ee-d7f2154ad048)
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/a2c73f96-b428-4341-bb05-a10413d32310)
![image](https://github.com/Gozargah/Marzban-node/assets/93261532/43806332-ddff-4d12-945c-fd3d4a91a9e6)
Can't connect to CF ports either

**Comment by kastov** [comment]
It is not an issue. 
If you domain proxied with CF - you can't connect node using that domain name. 
Disable CF proxying or use IP address. 

Please close this issue.

**Comment by realartin** [comment]
you must use http ports not https

**Comment by M03ED** [comment]
> ![image](https://private-user-images.githubusercontent.com/93261532/297661909-0c6955ef-6ec6-421f-80ee-d7f2154ad048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjcyMjcsIm5iZiI6MTcwNTU2NjkyNywicGF0aCI6Ii85MzI2MTUzMi8yOTc2NjE5MDktMGM2OTU1ZWYtNmVjNi00MjFmLTgwZWUtZDdmMjE1NGFkMDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZjQyMTEwNDUwMTNmYzYyYTgyMzMzNzFlOGYwYWRhYjBkZTMzNWY4YjFhOTA4OGJkMmM0YzU5Y2Q4NTMxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1W0pikj6nnQGY6dufVbnjG0IJyqyMykmQVQw7KvmoOk) ![image](https://private-user-images.githubusercontent.com/93261532/297661991-a2c73f96-b428-4341-bb05-a10413d32310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjcyMjcsIm5iZiI6MTcwNTU2NjkyNywicGF0aCI6Ii85MzI2MTUzMi8yOTc2NjE5OTEtYTJjNzNmOTYtYjQyOC00MzQxLWJiMDUtYTEwNDEzZDMyMzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MzIxNzI3N2U1ZWFlMjI4OTU4ZGU5OWU2NjEwZTllMThkMWE0NjE1MjNkMzRjMzZiYTUxNDBmNDFjZWM4NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CWpirvoaZaZnVrQFFEn9Ki6osrXeg6lwjzwoyW8Q5aY) ![image](https://private-user-images.githubusercontent.com/93261532/297662788-43806332-ddff-4d12-945c-fd3d4a91a9e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjcyMjcsIm5iZiI6MTcwNTU2NjkyNywicGF0aCI6Ii85MzI2MTUzMi8yOTc2NjI3ODgtNDM4MDYzMzItZGRmZi00ZDEyLTk0NWMtZmQzZDRhOTFhOWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWZmNzg2ZWIyMzdkOWVlYTJjNGQ2YzQ4YTFiYzZjMDFmNmZkODhjZDdkYjIwZGYzZTZlODg2NmU3NTQxM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-C5B78hn6Qw_FqSe89ND8Rlvu4TDv0nhZ5zlQeqDlk4) Can't connect to CF ports either

there is no need to use cdn between main server and node server 
cloudflare its for user connection to node server , instead of putting domain in node setting use server ip and some random ports
