### ISSUE TITLE
دسترسی به کانفیگ

### ISSUE THREAD

**Issue by Golden-Source** [Gozargah/Marzban-node#35]
با سلام و عرض ادب ما میخواهیم هر نود رو یک تانل مجزا بزنیم و توی سایت ما چطور میتونیم دسترسی به xray_config.json کنیم یا داخل کامند لاین؟

**Comment by realartin** [comment]
@Golden-Source لازم به xray_config.json نیست ، شما میتونید هر نود رو ی تانل مجزا بزنید و سپس تانل را در بخش هاست ستینگ به عنوان ادرس اضافه کنید

**Comment by Golden-Source** [comment]
@realartin تانلی که ما میخواهیم بزنیم روی xray_config هست میتونید بیشتر راهنمایی کنید؟

**Comment by realartin** [comment]
@Golden-Source میشه اطلاعات بیشتری در رابطه با نحوه تانل زدن در اختیار من قرار بدید تا بتونم بهتر راهنمایی کنم

**Comment by realartin** [comment]
@Golden-Source شما میتونید از روش :
https://github.com/Gozargah/Marzban/discussions/473

استفاده کنید و در بخش اتباند داخل هسته ایکس ری در پنل مستر اتباند مدنظر خودتون رو قرار بدهید

**Comment by Golden-Source** [comment]
متوجه شدم ، ما برای اینکه بتونیم برای هر نود تانل مخصوص بزنیم میایم از inboundTag هاش استفاده میکنیم و روت میزنیم میگیم که هر ریکوستی اومد برای این inboundTag به outboundTag خارج بره درسته؟
@realartin

**Comment by realartin** [comment]
@Golden-Source اگر بتونید تانل پنل به پنل رو صحیح اجرا کنید بله میتونید با اینباند تگ یا در بخش روتینگ با روت کردن ترافیک به اتباند خاص این مشکل رو هم حل کنید

**Comment by Golden-Source** [comment]
@realartin 
تشکر از شما بابت راهنمایی ، یک ابهامی برای من هست ما اگر از قبل برای outbounds تانلی زده باشیم برای اینکه بخواهیم مدیریت لازم رو داشته باشیم میتونیم مثلا دوتا outbounds ادد کنیم و توی روت بگیم این برای اینباند خاص باشه و این برای همه؟
چون من از چند نوع تانل استفاده میکنم و میخوام هر اینباند یک سرور جداگانه بره

**Comment by realartin** [comment]
@Golden-Source بله امکانش هست که هر اتباند رو به مسیر خاصی بفرستید
