### ISSUE TITLE
Revert the last PR please 

### ISSUE THREAD

**Issue by mikeesierrah** [Gozargah/Marzban-node#38]
فایل env شاید اصولی تر باشه برای نود ها ولی کار یوزر هارو در مرزبان نود سخت تر میکنه - چون الان اگه بخوایم به این شکل پیش بریم و نود هارو به چند پنل وصل کنیم باید برای هر پنل ی env  جدید درست کنیم و کار اموزش رو سخت تر میکنه - داکیومنت هم برای راحتی به اون شکل قبلی اموزش میده در نتیجه این حالت پیشفرض جدید تا حدی بلااستفاده میمونه - حال تصمیم با خودتونه ولی شخصا بنظرم حالت قبلی برای نود ها سر راست تر بوده

**Comment by iamtheted** [comment]
شدیدا موافقم، لطفا مرزبان نود قبلی را پس بدهید. 🥹

**Comment by fodhelper** [comment]
no one forced you to use env_file
just put the needed environment variables inside your docker-compose file and run it!

**Comment by mikeesierrah** [comment]
It seems you didn't understand what I meant , it's fine
