### ISSUE TITLE
مشکل وب سوکت در اکس ری ورژن  1.8.10 

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban-node#41]
سلام و احترام، کارشناسان محترم
در Wmess وب سوکت پشت کلود فلر  (استفاده از پورتهای http کلود فلر)   در اکس ری ورژن  1.8.10  مشکل وجود داره و کانفیگ متصل نمیشه ، در ورژن های پاینتر مشکلی نیست - این مشکل فقط در نودهای مرزبان مشاهده میشه و در پنلهای دیگه نیست، خواهشمند است در صورت امکان  راهنمایی فرمائید .

![image](https://github.com/Gozargah/Marzban-node/assets/103871792/3ab6959c-805a-4b41-8295-a7a08afec6f3)

![image](https://github.com/Gozargah/Marzban-node/assets/103871792/c8cd20a6-9b48-4d0f-8393-e360d41a9318)
https://github.com/XTLS/Xray-core/releases

**Comment by M03ED** [comment]
این مورد ربطی به مرزبان نداره ، در نسخه حدید وقتی در هسته از host برای ws استفاده می کنید فقط با همون host میتونید به این اینباند متصل بشید

**Comment by yaramahmadi** [comment]
> قتی در هسته از host برای ws ا

سلام
ممنون از پاسخگویی، اما متوجه نشدم دقیق منظورتونو
خواهشمند است  با توجه مواردی که عرض کردم در مورد استفاده از پورت های http در کلود فلر در ws روشنتر بیان فرمائید
سپاس

**Comment by M03ED** [comment]
در صورتی مشکل رفع شده issue رو ببندید
