### ISSUE TITLE
[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

### ISSUE THREAD

**Issue by fractalshine** [Gozargah/Marzban-node#42]
Followed by your guidlines can't pair panel and node. Receiveing error:
[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

**Comment by fractalshine** [comment]
I got it. Some wrong translation from farsi, and bad example in docs

**Comment by ultraleks** [comment]
> I got it. Some wrong translation from farsi, and bad example in docs

Please, tell me, how is right?

**Comment by fractalshine** [comment]
Just uncomment those line 
`# SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"`
in
https://github.com/Gozargah/Marzban-node/blob/master/docker-compose.yml
