### ISSUE TITLE
marzban-node has a lot of resource usage

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban-node#48]
Hi, how can i fix this? 
![image](https://github.com/Gozargah/Marzban-node/assets/109550653/9ea723a7-a326-44fa-868c-8e37aeebc873)

**Comment by SaintShit** [comment]
Hi, would you show which process is taking resources?

**Comment by m0x61h0x64i** [comment]
yes, main.py

I cant send picture because I already restarted docker container.

It solves issue temporary, I will need to restart container soon.

After restart memory usage was 600 500 MB now its  this:

![image](https://github.com/Gozargah/Marzban-node/assets/109550653/2b3a7b6a-193e-4249-8c12-7e3041f3e9d6)

**Comment by m0x61h0x64i** [comment]
CPU usage of main.py was 150% when i checked it using docker stats

**Comment by m0x61h0x64i** [comment]
yesterday before sleep memory usage was 2.7 GB after i wake up memory usage is 600 MB but my docker container was restarted automatically 40 min ago!
![image](https://github.com/Gozargah/Marzban-node/assets/109550653/b1c63c66-ec2c-4b34-8d76-a7caed405fc3)

**Comment by m0x61h0x64i** [comment]
today after last restart memory usage increased from 600MB to 1900MB then 2600MB and now without restart its like this:
![image](https://github.com/Gozargah/Marzban-node/assets/109550653/40d01cbc-78e1-4e61-9fed-ab4a0008a26d)
![image](https://github.com/Gozargah/Marzban-node/assets/109550653/953fd9df-2287-45f5-b55b-67e5c72103d3)
memory increase problem is just for node, for master mem usage is between 2.4GB ~ 2.7GB

**Comment by m0x61h0x64i** [comment]
main server is now this:
![image](https://github.com/Gozargah/Marzban-node/assets/109550653/82cb0b27-95b5-40b7-8ded-5c05ca1b45f2)
i guess no way to fix this, since users could not have good connection on the second server its ram was 600MB all the day, but now all are using main server so this time main server ram increased from 2.4GB ~ 2.7GB to this.
