### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tbehzad76** [Gozargah/Marzban-node#5]
in marzban panel display this Error:
[Errno 8] Exec format error: '/usr/local/bin/xray' -> None ========= Remote Traceback (1) ========= Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 356, in _dispatch_request res = self._HANDLERS[handler](self, *args) File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 837, in _handle_call return obj(*args, **dict(kwargs)) File "/code/service.py", line 100, in start raise exc File "/code/service.py", line 72, in start self.core = XRayCore(executable_path=XRAY_EXECUTABLE_PATH, File "/code/xray.py", line 110, in __init__ self.version = self.get_version() File "/code/xray.py", line 143, in get_version output = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('utf-8') File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "/usr/local/lib/python3.10/subprocess.py", line 503, in run with Popen(*popenargs, **kwargs) as process: File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) OSError: [Errno 8] Exec format error: '/usr/local/bin/xray'

in node server log:
ERROR: [Errno 8] Exec format error: '/usr/local/bin/xray'

**Comment by SaintShit** [comment]
Hi, thanks for sharing.
What is the specification of your server?

**Comment by tbehzad76** [comment]
Linux node-de 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:25:19 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by pbooyq** [comment]
@tbehzad76 Hi

**Comment by ArshaShk** [comment]
@tbehzad76 سلام

**Comment by tbehzad76** [comment]
سلام

**Comment by ArshaShk** [comment]
@tbehzad76 خوب هستید
ما یک عده آدم کرم دار هستیم
میتونید به تخمتون بگیرید
با تشکر تیم کرمداران

**Comment by Kup1ng** [comment]
@ArshaShk منم کرم دارم خوشبختم

**Comment by SaintShit** [comment]
32fcb883584aeab8ae6c7e29de78c420a774ba38
