### ISSUE TITLE
مشکل در نود

### ISSUE THREAD

**Issue by ahmadrezaei** [Gozargah/Marzban-node#8]
سلام
من یه نود اضافه کردم، توی لیست هاست ها هم اد شد ولی توی کانفیگ های سابسکرایب نمیاد
حتی کل کانفیگ ها رو هم کپی کردم توی کلاینت بازم نیومد

**Comment by SaintShit** [comment]
سلام
حل شده مشکلتون؟

**Comment by amirmhm** [comment]
با سلام
برای من اصلا گزینه ی دانلود سرتیفیکیت نشون داده نمیشه و کلا خالیه.
![Screenshot 2024-02-24 123247](https://github.com/Gozargah/Marzban-node/assets/63209512/160b14a4-cd6e-4368-9efc-8afffb3d2cb1)

**Comment by iamtheted** [comment]
> با سلام
> برای من اصلا گزینه ی دانلود سرتیفیکیت نشون داده نمیشه و کلا خالیه.
> ![Screenshot 2024-02-24 123247](https://github.com/Gozargah/Marzban-node/assets/63209512/160b14a4-cd6e-4368-9efc-8afffb3d2cb1)
> 

نسخه پنلت چنده؟ انتهای صفحه نسخه رو زده

**Comment by amirmhm** [comment]
v0.3.1

**Comment by amirmhm** [comment]
> > با سلام
> > برای من اصلا گزینه ی دانلود سرتیفیکیت نشون داده نمیشه و کلا خالیه.
> > ![Screenshot 2024-02-24 123247](https://private-user-images.githubusercontent.com/63209512/307507108-160b14a4-cd6e-4368-9efc-8afffb3d2cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjQxODAsIm5iZiI6MTcwODc2Mzg4MCwicGF0aCI6Ii82MzIwOTUxMi8zMDc1MDcxMDgtMTYwYjE0YTQtY2Q2ZS00MzY4LTllZmMtOGFmZmZiM2QyY2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA4MzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYzVmYjkyNmRlN2Q4YjFjMzA4ZmU2YmE2NWIyNjdmNTMwOWU4MTY3MTk3OTc3ZjgxOGRhNmViMDM4YmZkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SUdcDzliW6UOHnn25CCkQ2vOmJSY1u9axUb7eY_2hGg)
> 
> نسخه پنلت چنده؟ انتهای صفحه نسخه رو زده

v0.3.1

**Comment by M03ED** [comment]
> v0.3.1

الان ورژن 0.4.6 هستیم 
لطفا سعی کنید همیشه پنل تون رو اپدیت نگه دارید

**Comment by amirmhm** [comment]
> > v0.3.1
> 
> الان ورژن 0.4.6 هستیم لطفا سعی کنید همیشه پنل تون رو اپدیت نگه دارید

خیلی ممنون 
ببخشید من توی توضیحات نحوه ی آپدیت پنل رو نتونستم پیدا کنم

**Comment by M03ED** [comment]
`marzban help`
